//import { Theme } from '@react-navigation/native';
// import { DefaultTheme } from 'styled-components';

export interface DefaultTheme {
  dark: boolean;
  colors: {
    primary: string;
    secondary: string;
    background: string;
    card: string;
    text: string;
    border: string;
    notification: string;
  };
}

export const defaultTheme: DefaultTheme = {
  dark: false,
  colors: {
    primary: 'rgb(0, 122, 25)',
    secondary: 'rgb(0,0,0)',
    background: 'rgb(242, 242, 242)',
    card: 'rgb(255, 255, 255)',
    text: 'rgb(28, 28, 30)',
    border: 'rgb(216, 216, 216)',
    notification: 'rgb(255, 59, 48)',
  },
};

// export const lightTheme: DefaultTheme = {
//   mode: 'light',
//   borderRadius: '16px',
//   margin: '5px 0px',
//   padding: '5px 8px',
//   tokens: {
//     colors: {
//       primaryD1: '#14DA70',
//       primaryD2: '#2CDE7E',
//       primaryD3: '#43E18D',
//       primaryD4: '#5BE59B',
//       primaryD5: '#72E9A9',
//       primaryL1: '#8AEDB8',
//       primaryL2: '#A1F0C6',
//       primaryL3: '#B9F4D4',
//       primaryL4: '#CCFFE1',
//       primaryL5: '#E8FBF1',
//       secondaryD1: '#055AEE',
//       secondaryD2: '#1E6BF0',
//       secondaryD3: '#3180FF',
//       secondaryD4: '#508CF3',
//       secondaryD5: '#699CF5',
//       secondaryL1: '#82ADF7',
//       secondaryL2: '#9BBDF8',
//       secondaryL3: '#B4CEFA',
//       secondaryL4: '#BDDEFF',
//       secondaryL5: '#E6EFFD',
//       tertiaryD1: '#FFC7A1',
//       tertiaryD2: '#FFCDAA',
//       tertiaryD3: '#FFD2B4',
//       tertiaryD4: '#FFD8BD',
//       tertiaryD5: '#FFDDC7',
//       tertiaryL1: '#FEE3D2',
//       tertiaryL2: '#FFE9D9',
//       tertiaryL3: '#FFEFE4',
//       tertiaryL4: '#FFF4EC',
//       tertiaryL5: '#FFF9F6',
//       lightBlueD1: '#A4EEF8',
//       lightBlueD2: '#ADF0F9',
//       lightBlueD3: '#B6F1F9',
//       lightBlueD4: '#C9F5FA',
//       lightBlueD5: '#C8F5FB',
//       lightBlueL1: '#D2F7FC',
//       lightBlueL2: '#DBF8FC',
//       lightBlueL3: '#E5FAFD',
//       lightBlueL4: '#EDFCFE',
//       lightBlueL5: '#F6FDFE',
//       darkBlueD1: '#153243',
//       darkBlueD2: '#2C4756',
//       darkBlueD3: '#455B69',
//       darkBlueD4: '#5B707B',
//       darkBlueD5: '#73848E',
//       darkBlueL1: '#8A99A1',
//       darkBlueL2: '#A1ADB4',
//       darkBlueL3: '#B9C2C7',
//       darkBlueL4: '#D0D6D9',
//       darkBlueL5: '#E8EBEC',
//       surfaceL1: '#E8F1F2',
//       surfaceL2: '#EAF2F3',
//       surfaceL3: '#EDF4F5',
//       surfaceL4: '#EFF5F6',
//       surfaceL5: '#F4F8F9',
//       none: 'white',
//       default_accent: '#B7B7B7',
//       success_accent: '#30af54',
//       warning_accent: '#FFCC47',
//       danger_accent: '#D54141',
//       success_state: '#1A9E40',
//       neutral: '#5FC8FF',
//       default_surface: '#EAEAEA',
//       success_surface: '#D7F2DF',
//       warning_surface: '#FFF5DA',
//       danger_surface: '#FFE3E7',
//       neutral_surface: '#BDE2F5',
//       disabledButtonTextColor: '#A1ADB4',
//       disabledButtonColor: '#D0D6D9',
//       buttonTextColor: '#EFF5F6',
//       buttonColor: '#14DA70',
//       switchOutline: '#055AEE',
//       modeBackground: 'transparent',
//       focusedTextInput: '#055AEE',
//       textInput: '#E8EBEC',
//       errorTextInput: '#FF4D64',
//       opposing: '#153243',
//       soft: '#A3B7CC',
//       exitPoint: '#EB5757',
//       banner: '#E8FBF1',
//       brandColorsGrayStreet: '#F4F8F9',
//     },
//     states: {
//       default_accent: '#B7B7B7',
//       success_accent: '#05892B',
//       warning_accent: '#FFCC47',
//       danger_accent: '#D54141',
//       neutral: '#5FC8FF',
//       default_surface: '#EAEAEA',
//       success_surface: '#D7F2DF',
//       warning_surface: '#FFF5DA',
//       danger_surface: '#FFE3E7',
//       neutral_surface: '#BDE2F5',
//     },
//   },
//   colors: {
//     text: {
//       white: '#fff',
//       primary: '#5B7C9F',
//       secondary: '#233950',
//       legend: '#9BB1C8',
//       soft: '#A3B7CC',
//       black: '#12141A',
//       error: '#EB5757',
//     },
//     error: '#EB5757',
//     background: '#ecf1f7',
//     primary: '#9BB1C8',
//     secondary: '#CCD8E5',
//     soft: '#DBE3EC',
//     third: '#6483A5',
//     line: '#6B8DB0',
//     backgroundModal: '#E1E8F3',
//     negativeValues: '#FF7168',
//     positiveValues: '#6CC6B0',
//     transparent: 'transparent',
//     white: '#FFFFFF',
//     gray: '#DADADA',
//     opposing: '#153243',
//     standard: '#FFFFFF',
//   },
// };
